Traceback (most recent call last):
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/preprocessing/data_preprocessing.py", line 388, in <module>
    main()
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/preprocessing/data_preprocessing.py", line 381, in main
    preprocessing(meal_type, preprocess_log)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/preprocessing/data_preprocessing.py", line 285, in preprocessing
    train_models_by_sparsity(bci_df, meal_type)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/train_portion_model.py", line 80, in train_models_by_sparsity
    fold_macro_metrics, fold_micro_metrics, test_metrics = train_portion_model(reduced_data, nn.results_save_path, meal_type, wb_group_name, sparsity_model_train_log)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/train_portion_model.py", line 18, in train_portion_model
    fold_macro_metrics, fold_micro_metrics, best_model = cross_validation(
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/utils/model_utils.py", line 102, in cross_validation
    model.train(X_fold_train, y_fold_train, X_fold_val, y_fold_val, log)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/utils/models.py", line 104, in train
    self.model.fit(
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/keras/src/engine/training.py", line 1783, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 831, in __call__
    result = self._call(*args, **kwds)
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 867, in _call
    return tracing_compilation.call_function(
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compilation.py", line 139, in call_function
    return function._call_flat(  # pylint: disable=protected-access
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/concrete_function.py", line 1264, in _call_flat
    return self._inference_function.flat_call(args)
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 217, in flat_call
    flat_outputs = self(*args)
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 252, in __call__
    outputs = self._bound_context.call_function(
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 1479, in call_function
    outputs = execute.execute(
  File "/home/unixftwx/anaconda3/envs/diet_rec/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
KeyboardInterrupt