Traceback (most recent call last):
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 226, in <module>
    main()
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 220, in main
    iteratively_train_models(data, meal_type)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 211, in iteratively_train_models
    result = train_portion_model(reduced_data, nn.model_save_path, meal_type, wb_group_name)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 166, in train_portion_model
    fold_metrics_avg, fold_metrics_agg, best_model = cross_validate_model(X_train, y_train, logpath, meal_type, config, f'drp_portion_model', wb_group_name)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 131, in cross_validate_model
    nn.train(X_fold_train, y_fold_train, X_fold_val, y_fold_val)
  File "/mnt/e/Personal/UC Davis/Research/Ilias/AIFS Projects/diet_recommendation/meal_recommender/src/training/portion_model.py", line 55, in train
    self.model.fit(
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
    return fn(*args, **kwargs)
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/keras/src/engine/training.py", line 1742, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 825, in __call__
    result = self._call(*args, **kwds)
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/polymorphic_function.py", line 857, in _call
    return self._no_variable_creation_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/tracing_compiler.py", line 148, in __call__
    return concrete_function._call_flat(
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 1349, in _call_flat
    return self._build_call_outputs(self._inference_function(*args))
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 196, in __call__
    outputs = self._bound_context.call_function(
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 1457, in call_function
    outputs = execute.execute(
  File "/home/unixftwx/anaconda3/envs/drp/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
KeyboardInterrupt